# Generated by Django 5.2.7 on 2025-10-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('1', 'Profesor'), ('2', 'Estudiante')], default='2', max_length=1),
        ),
    ]
