# Generated by Django 5.2.7 on 2025-11-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cuenta_bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='intentos_fallidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
