# Generated by Django 5.2.7 on 2025-11-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cuenta_bloqueada_user_intentos_fallidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cuenta_bloqueada',
            field=models.BooleanField(db_column='is_locked', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado_suscripcion',
            field=models.BooleanField(db_column='subscription_status', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_fin_suscripcion',
            field=models.DateField(blank=True, db_column='subscription_end_date', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_inicio_suscripcion',
            field=models.DateField(blank=True, db_column='subscription_start_date', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='intentos_fallidos',
            field=models.PositiveIntegerField(db_column='failed_attempts', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('1', 'Profesor'), ('2', 'Estudiante')], db_column='role', default='2', max_length=1),
        ),
    ]
