# Generated by Django 5.2.7 on 2025-11-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_cuenta_bloqueada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='estado_suscripcion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_fin_suscripcion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fecha_inicio_suscripcion',
        ),
    ]
