# Generated by Django 5.2.7 on 2025-10-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion_corta', models.TextField(max_length=250)),
                ('descripcion_detallada', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('duracion', models.PositiveIntegerField()),
                ('gamificacion', models.BooleanField(default=False)),
                ('tipo_gamificacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
