# Generated by Django 5.2.7 on 2025-11-09 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_created_at_course_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categoria',
            field=models.CharField(db_column='category', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='codigo',
            field=models.CharField(blank=True, db_column='code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='descripcion_corta',
            field=models.TextField(db_column='short_description', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='descripcion_detallada',
            field=models.TextField(blank=True, db_column='long_description', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, db_column='duration_hours', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], db_column='status', default='publicado', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='gamificacion',
            field=models.BooleanField(db_column='gamification_enabled', default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='imagen_portada',
            field=models.URLField(blank=True, db_column='cover_image_url', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='nivel',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], db_column='level', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='profesor',
            field=models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='tipo_gamificacion',
            field=models.CharField(blank=True, choices=[('memoria', 'Juego de memoria')], db_column='gamification_type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='titulo',
            field=models.CharField(db_column='title', max_length=150),
        ),
    ]
