# Generated by Django 5.2.7 on 2025-11-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursesubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imagen_portada',
            field=models.TextField(blank=True, db_column='cover_image_url', null=True),
        ),
    ]
