# Generated by Django 5.2.7 on 2025-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygamepair',
            name='image_url',
        ),
        migrations.AddField(
            model_name='memorygamepair',
            name='question_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
