# Generated by Django 5.2.7 on 2025-11-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_memorygamepair_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygamepair',
            name='juego',
        ),
    ]
