# Generated by Django 5.2.7 on 2025-11-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_memorygamepair_juego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygamepair',
            name='pair_id',
        ),
    ]
