# Generated by Django 5.2.7 on 2025-11-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_memorygamepair_pair_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorygamepair',
            name='juego',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='games.memorygame'),
            preserve_default=False,
        ),
    ]
