# Generated by Django 5.2.7 on 2025-11-15 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_imagen_portada'),
        ('games', '0005_memorygamepair_juego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorygame',
            name='leccion',
        ),
        migrations.AddField(
            model_name='memorygame',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memory_games', to='courses.course'),
            preserve_default=False,
        ),
    ]
