# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='curso',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='archivo',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='orden',
            new_name='order',
        ),
    ]

