# Generated by Django 5.2.7 on 2025-11-09 23:14

import django.db.models.deletion
import django.utils.timezone
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.lesson_file_path, validators=[lessons.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='titulo',
        ),
    ]
