# Generated by Django 5.2.7 on 2025-11-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.TextField(blank=True, help_text='PDF en base64', null=True),
        ),
    ]
