# Generated by Django 5.2.7 on 2025-11-16 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
    ]
